version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense-sql
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

  api:
    build:
      context: .
      dockerfile: ExpenseSystem.API/Dockerfile
    container_name: expense-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ExpenseSystemDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True"
      JwtSettings__SecretKey: "THIS_IS_A_SUPER_SECRET_KEY_123456789"
      JwtSettings__Issuer: "ExpenseSystemAPI"
      JwtSettings__Audience: "ExpenseSystemClient"
      JwtSettings__ExpiryHours: 24
    ports:
      - "5050:8080"
    restart: always

volumes:
  sql_data: